**Домашнее задание к лекции.

Задание 1**
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
  - оценка 2 и меньше - низкий рейтинг
  - оценка 4 и меньше - средний рейтинг
  - оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [26]:
import pandas as pd
stats = pd.read_csv('ratings.csv')
def classifier(rating):
    
    if rating <= 2:
        return 'низкий рейтинг'
    if 2 < rating <= 4:
        return 'средний рейтинг'
    if rating == 4.5:
        return 'высокий рейтинг'
    if rating == 5:
        return 'высокий рейтинг'
        
stats['class'] = stats['rating'].apply(classifier)
stats.tail(300)

        userId  movieId  rating   timestamp            class
100536     610    91485     3.0  1493846912  средний рейтинг
100537     610    91500     4.0  1493845427  средний рейтинг
100538     610    91529     4.5  1493844922  высокий рейтинг
100539     610    91535     3.5  1493846223  средний рейтинг
100540     610    91542     3.5  1493847422  средний рейтинг
...        ...      ...     ...         ...              ...
100831     610   166534     4.0  1493848402  средний рейтинг
100832     610   168248     5.0  1493850091  высокий рейтинг
100833     610   168250     5.0  1494273047  высокий рейтинг
100834     610   168252     5.0  1493846352  высокий рейтинг
100835     610   170875     3.0  1493846415  средний рейтинг

[300 rows x 5 columns]

Задание 2 Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце 'region' пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим 'undefined'.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

In [5]:
import pandas as pd
region = pd.read_csv('keywords.csv.')
region.head()

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2          порно  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [10]:
geo_data = ({'Центр': ['вк', 'ютуб', 'ярославль'],
             'Северо-Запад': ['петербург', 'одноклассники', 'мурманск'],
             'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']})
df = pd.read_csv('keywords.csv')
def regions(keyword):
    for k, v in geo_data.items():
        for i in v:
            if i in keyword:
                return k
            
        return  'undefined'
df['region'] = df['keyword'].apply(regions)
df.head(300)

                 keyword     shows     region
0                     вк  64292779      Центр
1          одноклассники  63810309  undefined
2                  порно  41747114  undefined
3                   ютуб  39995567      Центр
4              вконтакте  21014195      Центр
..                   ...       ...        ...
295                 xnxx    512717  undefined
296            гиг порно    565866  undefined
297         киви кошелек    516880  undefined
298                рутор    511758  undefined
299  первый канал онлайн    529164  undefined

[300 rows x 3 columns]

In [13]:
for k, v in geo_data.items():
    for i in v:
        print(i)

вк
ютуб
ярославль
петербург
одноклассники
мурманск
владивосток
сахалин
хабаровск

**Задание 3 (бонусное)**
Есть мнение, что "раньше снимали настоящее кино, не то что сейчас". Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

1. В переменную years запишите список из всех годов с 1950 по 2010.

2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
  - для каждой строки пройдите по всем годам списка years
  - если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
  - если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец 'year'

4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца 'year' и отсортируйте результат по убыванию рейтинга


**Важно! При копировании юпитер ноутбука изменяет кавычки ’ на ` , что может способствовать ошибки в коде. В данной ситуации необходимо их просто заменить.**